@id("6b9aac1b-7064-4a0b-b541-dbafac71f3ac")
@nodeType("21")
@postSQL("SELECT CURRENT_TIMESTAMP() AS POST_SQL_EXECUTED;")
SELECT
CURRENT_TIMESTAMP() AS PRE_SQL_EXECUTED,
     "ID" AS "ID",
     "SNAPSHOT_DATE" AS "SNAPSHOT_DATE",
     "VALUE" AS "VALUE"
FROM {{ ref('WORK', 'TEST_CLUSTER') }} "TEST_CLUSTER"